library(readxl)
Accidents <- read_excel("C:/Users/Javier Villanueva/Desktop/Navarra/Semestre 1/Machine Learning/Accidents.xlsx")
View(Accidents)
df <- na.omit(Accidents)
library(caTools)
library(lattice)
library(e1071)
df$DriversGender=factor(df$DriversGender)
str(df)
table(df$DriversGender)
xyplot(df$DriversAge ~  df$VehiclesAge, group=DriversGender, data=df)
xyplot(df$NumberOfCasualties ~  df$NumberOfVehicles, group=DriversGender, data=df)
split <- sample.split(df$DriversGender, SplitRatio = 0.8)
train <- subset(df, split == TRUE)
test <- subset(df, split == FALSE)
table(train$DriversGender)
m <- naiveBayes(DriversGender ~ ., data = train, subset)
p <- predict(m, test, threshold = 0.05)
t <- ftable(Predicted=p, Correct=test$DriversGender)
ftable(Predicted=p, Correct=test$DriversGender)
accuracy <- function(x){sum(diag(x))/sum(x)}
accuracy(t)
